apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustom-default
resources:
- deployment.yaml
- service.yaml
- route.yaml

secretGenerator:
- name: quay-pull-secret
  files:
   - .dockerconfigjson=dockerconfigjson
  type: "kubernetes.io/dockerconfigjson"

patches:
  - patch: |-
      - op: add
        path: /imagePullSecrets/-
        value:
          name: quay-pull-secret
    target:
      kind: ServiceAccount
      name: default

commonLabels:
  app: api-default

#namePrefix: api-
#nameSuffix: -default
