# Default values for mongodb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mongodbUsername: mongodb-user

# Default values for mongodb.
# This is a YAML-formatted file.

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  tag: "5.0.9-ubi8"
  repository: 'docker.io/mongodb/mongodb-community-server'

service:
  type: ClusterIP
  port: 27017


resources:
  limits:
    cpu: "250m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

mongodbVolumeClaim:
  accessModes:
    - ReadWriteOnce
  storageClass: ""
  size: 5Gi
  volumeMode: Filesystem
