apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-goodbye
  namespace: tkn-pipelines
spec:
  params:
  - name: username
    type: string
  tasks:
    - name: hello
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: hello
          - name: namespace
            value: tkn-task
    # - name: goodbye
    #   runAfter:
    #     - hello
    #   taskRef:
    #     name: goodbye
    #   params:
    #   - name: username
    #     value: $(params.username)