apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-goodbye
  namespace: tkn-pipelines
spec:
  params:
  - name: username
    type: string
  tasks:
    - name: hello
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: hello
          - name: namespace
            value: tkn-task
    - name: goodbye
      runAfter:
        - hello
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/Carlos-ZRM/openshift-app.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tekton/crear_pipeline/2_TASK_GoodBye.yaml
      params:
      - name: username
        value: $(params.username)