apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-api-prod
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/Carlos-ZRM/openshift-app.git
    targetRevision: HEAD
    path: jupyter/ocp-api/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: api-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true