apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-kubeconform
spec:
  params:
    - name: helm_directory
      description: Directory where the Helm chart is located
      type: string
      default: "."
  results:
    - name: command_result
      description: Salida del comando ejecutado
  workspaces:
    - name: source
      optional: false
      description: Workspace del task
  steps:
    - name: shell
      image: image-registry.openshift-image-registry.svc:5000/xpk/kubeconform:latest
      script: |
        #!/bin/bash
        helm template $(params.helm_directory) > template.yaml
        kubeconform -strict \
          -schema-location default \
          -schema-location https://raw.githubusercontent.com/garethr/openshift-json-schema/master \
          -summary template.yaml | tee "$(results.command_result.path)"
