---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: kubeconform
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: kubeconform-build
spec:
  source:
    type: Git
    git:
      uri: https://github.com/Carlos-ZRM/openshift-app.git
    contextDir: tekton/tasks/helm-kubeconform
  strategy:
    type: Docker
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'kubeconform:latest'
  triggers:
    - type: GitHub
      github:
        secret: your-github-secret
    - type: ConfigChange
    - type: ImageChange