apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aap-operator
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'aap-{{cluster}}'
    spec:
      project: default
      source:
       repoURL: git@github.com:Carlos-ZRM/openshift-app.git
       path: argocd-operators/aap
       targetRevision: HEAD
      destination:
        server: '{{url}}'
        
