apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: openshift-storage.cephfs.csi.ceph.com
    volume.kubernetes.io/storage-provisioner: openshift-storage.cephfs.csi.ceph.com
  creationTimestamp: "2026-08-20T23:16:43Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: payload
  namespace: xpk
  resourceVersion: "2184692"
  uid: 9cfef065-7c83-47d3-8ca1-e9d4090fabaa
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-external-storagecluster-cephfs
  volumeMode: Filesystem
  volumeName: pvc-9cfef065-7c83-47d3-8ca1-e9d4090fabaa
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  phase: Bound
