kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-api
    app.kubernetes.io/component: {{ .Release.Name }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: {{ .Release.Name }}-api
        app: {{ .Release.Name }}-api
        app.kubernetes.io/component: {{ .Release.Name }}-api
        app.kubernetes.io/instance: {{ .Release.Name }}-api
    spec:
      containers:
        - name: api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8778
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: myapi-api-config
                  key: MONGO_URI
            - name: API_PORT
              value: "{{ .Values.api.port }}"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 13
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-03-03T03:59:17Z'
      lastTransitionTime: '2025-03-03T03:59:17Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-03-03T04:08:27Z'
      lastTransitionTime: '2025-03-02T20:41:42Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "api-5c9987bf9d" has successfully progressed.
