kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}-api
    weight: 100
  port:
    targetPort: {{ .Values.service.port }}-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
