{{- $namespace := .Release.Namespace }}
{{- $sourceSecret := lookup "v1" "Secret" $namespace .Values.sourceSecretName }}
{{- if and $sourceSecret (hasKey $sourceSecret "data") (hasKey $sourceSecret.data "MONGO_INITDB_ROOT_PASSWORD") }}
{{- $mongoUsername := index $sourceSecret.data "MONGO_INITDB_ROOT_USERNAME" | b64dec }}
{{- $mongoPassword := index $sourceSecret.data "MONGO_INITDB_ROOT_PASSWORD" | b64dec }}
{{- $mongoUri := printf "mongodb://%s:%s@%s/admin" $mongoUsername $mongoPassword .Values.mongoHostname }}

apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-api-config"
  namespace: {{ $namespace }}
type: Opaque
data:
  MONGO_URI: {{ $mongoUri | b64enc }}
{{- end }}