apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  argocd.argoproj.io/sync-wave: "-1"
  creationTimestamp: null
  name: system:openshift:scc:anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: qdrant
  namespace: qdrant
