kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: qdrant
spec:
  host: ""
  to:
    kind: Service
    name: qdrant
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
