apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  {{ .Release.Name }}-app
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  {{ .Release.Name }}-app
        image:  registry.redhat.io/jboss-webserver-5/jws58-openjdk17-openshift-rhel8
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  8080
          name:  {{ .Release.Name }}-app-8080
      restartPolicy: Always
