apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: Opaque
data:
  username: {{ .Values.username | b64enc }}
  password: {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "secret-basic-auth" }}
            {{- if $existingSecret }}
              {{ $existingSecret.data.password }}
            {{- else }}
              {{ randAlphaNum 16 | b64enc }}
            {{- end }}