kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-error
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  spec:
    ipFamilies:
      - IPv4
    ports:
      - name: 3001-tcp
        protocol: TCP
        port: 3001
        targetPort: 3001
    internalTrafficPolicy: Cluster
    type: ClusterIP
    ipFamilyPolicy: SingleStack
    sessionAffinity: None
    selector:
      app: api-usuario
      deployment: api-usuario
