apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-svc
  labels:
    app: {{ .Release.Name }}-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}-app
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: {{ .Release.Name }}-app-8080
    protocol: TCP
    port: 8080
    targetPort: 8080