apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: triggerbinding-api
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: getting-started
    - name: gitrepositoryurl
      value: 'https://github.com/$(body.repository.full_name)'