---
apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig-secret
stringData:
  config.json: |
    {
      "auths" : {
        "quay.io" : {
          "auth" : "iamapikey"
        },
        "quay-registry-quay-openshift-operators.apps.cluster-r8f27.r8f27.sandbox470.opentlc.com": {
          "auth": "Y3JleWVzbWErYXBpX2FkbWluOlJEQjUwNTFXRTFRQzMxTzdVSDIwMVQzRUVOVTc0UU5ZTzhZM1lRT0lPMFFHOEFLSE02RVhCUjNLTjNBQ1M3TEM="
        }
      }

    }
