apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api-dev
resources:
- 01-PVC.yaml
#- 02-Pipeline-api.yaml
#- 03-CRB-Pipe-privileged.yaml
#- 04-imagestream.yaml
#- 05-Triggertemplate.yaml
#- 06-Triggerbinding.yaml
#- 07-Eventlistener.yaml
#- 08-Rutatrigger.yaml

commonLabels:
  pipeline: build-api

patches:
  - path: 01-PVC.yaml
    target:
      kind: PersistentVolumeClaim
      #name: pvc-git-api
      labelSelector: "pipeline=build-api"
  - patch: |-
      - op: replace
        path: /spec/storageClassName
        value: gp3-csi
