apiVersion: apps/v1
kind: Deployment
metadata:
  name:  apiimg
spec:
  selector:
    matchLabels:
      app: apiimg
  template:
    metadata:
      labels:
        app:  apiimg
    spec:
      containers:
      - name:  apiimg
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 300Mi
        env:
        - name: COLOR
          value: "yellow"
