apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/storageClassName
        value: gp3-csi
    target:
      kind: PersistentVolumeClaim
