apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-api
  namespace: cie
spec:
  params:
    - default: main
      description: The git revision
      name: gitrevision
    - description: The git repository url
      name: gitrepositoryurl
    - default: This is the default message
      description: The message to print
      name: message
    - description: The Content-Type of the event
      name: contenttype
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipelinerun-ci-openapi-
      spec:
        params:
          - name: repo-url
            value: >-
              https://gitea.apps.cluster-6j5fd.sandbox1230.opentlc.com/xpk/openapi.git
          - name: img-registry
            value: >-
              image-registry.openshift-image-registry.svc:5000/cie/pipeline-api:latest
          - name: img-context
            value: ./
          - name: img-dockerfile
            value: Containerfile
        pipelineRef:
          name: pipeline-api
        workspaces:
          - name: workspace-git
            persistentVolumeClaim:
              claimName: pvc-git-pipeline