apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-git-api
spec:
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem