kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{.Release.Name}}-mongodb-community-server
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Release.Name}}-mongodb-community-server
    app.kubernetes.io/component: {{.Release.Name}}-mongodb-community-server
    app.kubernetes.io/instance: {{.Release.Name}}-mongodb-community-server
    app.kubernetes.io/name: {{.Release.Name}}-mongodb-community-server
    app.kubernetes.io/part-of: {{.Release.Name}}-app
    app.openshift.io/runtime-namespace: {{.Release.Namespace}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb-community-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}-mongodb-community-server
        deployment: {{ .Release.Name }}-mongodb-community-server
        app.kubernetes.io/component: {{ .Release.Name }}-mongodb-community-server
        app.kubernetes.io/instance: {{ .Release.Name }}-mongodb-community-server
        app.kubernetes.io/name: {{ .Release.Name }}-mongodb-community-server
        app.kubernetes.io/part-of: {{ .Release.Name }}-app
        app.openshift.io/runtime-namespace: {{ .Release.Namespace }}
    spec:
      volumes:
        - name: mongodb-community-server-1
          emptyDir: {}
        - name: {{ .Values.mongodbVolumeClaim.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.mongodbVolumeClaim.name }}
      containers:
        - resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          terminationMessagePath: /dev/termination-log
          name: {{ .Release.Name }}-mongodb-community-server
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb-user
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb-user
                  key: MONGO_INITDB_ROOT_USERNAME
          ports:
            - containerPort: 27017
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mongodb-community-server-1
              mountPath: /data/configdb
            - name: {{ .Values.mongodbVolumeClaim.name }}
              mountPath: /data/db
          terminationMessagePolicy: File
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
