kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-mongodb-user
  namespace: {{ .Release.Namespace }}
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodbUsername | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "secret-basic-auth" }}
                              {{- if $existingSecret }}
                                {{ $existingSecret.data.password }}
                              {{- else }}
                                {{ randAlphaNum 16 | b64enc }}
                              {{- end }}
type: Opaque
