apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-git-pipeline
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem

