apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
#nameSuffix: -dev
namespace: api-dev
commonLabels:
  oper_env: dev
patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      labelSelector: "app=apiimg"
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/revisionHistoryLimit
        value: 2
      
    target:
      kind: Deployment
      labelSelector: "app=apiimg"

images:
- name: quay.io/rhdevelopers/bgd:default
  newTag: latest
- name: quay.io/rhdevelopers/bgd:latest
  newName: image-registry.openshift-image-registry.svc:5000/api-dev/api
