FROM registry.access.redhat.com/ubi9/python-312@sha256:306e4320c559d67c60874e3bb85c9f84afc84b66c350b3d4afe0abd65201d6e6

USER 0
COPY src .
RUN chown -R 1001:0 ./
USER 1001

RUN pip install -r requirements.txt

ENTRYPOINT python app.py