FROM registry.redhat.io/rhel9/python-311@sha256:37dd30f6013d1cc6c14383486f5fbcf805aae67cf243ca842a216b2cde7f02de 

USER 0
COPY src .
RUN chown -R 1001:0 ./
USER 1001

RUN pip install -r requirements.txt

ENTRYPOINT python app.py