apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd-app
  namespace: openshift-gitops
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/Carlos-ZRM/openshift-app.git'
      path: argocd-httpd/src
      targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: httpd-app-argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
