apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoapp-virtalization-pipelines
  namespace: openshift-gitops
spec:
  destination:
    namespace: virtualization-pipelines
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift-virtualization/tekton_tasks
    repoURL: https://github.com/Carlos-ZRM/openshift-app.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
#https://github.com/kubevirt/kubevirt-tekton-tasks/tree/main/release/tasks/execute-in-vm