apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoapp-python
  namespace: openshift-gitops
spec:
  destination:
    namespace: tomcat-virt-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift-virtualization/config_vm
    repoURL: https://github.com/Carlos-ZRM/openshift-app.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
