apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 0-image-stream.yaml
  - 1-build-config.yaml
  - 2-pvc.yaml
  - 3-deploy.yaml
  - 4-hpa.yaml
  - 5-svc.yaml
  - 6-route.yaml

commonLabels:
  app: app-base-test
  app.kubernetes.io/name: app-base-test
  app.kubernetes.io/component: backend
  app.kubernetes.io/instance: app-base-test



images:
  - name: is-app-base-test
    newName: image-registry.openshift-image-registry.svc:5000/my-namespace/is-app-base-test
    newTag: latest
#namePrefix: python-app-
