apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: net-cat-app
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: 'https://github.com/Carlos-ZRM/openshift-app.git'
        revision: main
        directories:
          - path: 'python-netcat-app/k8s/kustomize/*/overlays/*'
          - path: 'python-netcat-app/k8s/kustomize/*/base'
            exclude: true
  template:
    metadata:
      name: '{{index (splitList "/" .path.path) 3}}-{{index (splitList "/" .path.path) 5}}'
      namespace: openshift-gitops
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/Carlos-ZRM/openshift-app.git'
          path: '{{.path.path}}'
          targetRevision: main
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{index (splitList "/" .path.path) 3}}-{{index (splitList "/" .path.path) 5}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true