apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: velero
  namespace: openshift-adp
spec:
  backupLocations:
    - velero:
        config:
          profile: default
          region: us-west-1
        credential:
          key: cloud
          name: cloud-credentials
        default: true
        objectStorage:
          bucket: xpk-101-oadp
          prefix: velero
        provider: aws
  configuration:
    nodeAgent:
      enable: true
      uploaderType: restic
    velero:
      defaultPlugins:
        - openshift
        - aws
        - azure
        - kubevirt
        - csi
  snapshotLocations:
    - velero:
        config:
          profile: default
          region: us-west-1
        provider: aws
