apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipeline-python
spec:
  pipelineRef:
    name: install-python
  params:
    - name: vmName
      value: fedora-python-xpk
    - name: secretName
      value: ssh-secret
    - name: script
      value: "sudo dnf install python3 python3-devel  python3-pip -y"