apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: 'image-registry.openshift-image-registry.svc:5000/ns/test-netcat:latest'
  newName: 'image-registry.openshift-image-registry.svc:5000/test-netcat/test-netcat-py-3-11'
  newTag: 'latest'