apiVersion: v1
kind: Secret
metadata:
  name: authorized-keys
data:
  key:  |
    c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUZjaVlLRkhhV1puQUdGUXBJRGIwd280cmR5eTd1T2Y1Tm5sT2NJd2UvZnggY3JleWVzbWFAY3JleWVzbWEtbWFjCg==