apiVersion: 'kubevirt.io/v1'
kind: 'VirtualMachine'
metadata:
  annotations: {}
  labels:
    app: 'fedora-tomcat-xpk'
  name: 'fedora-tomcat-xpk'
  namespace: 'tomcat-virt-app'
spec:
  dataVolumeTemplates:
    - apiVersion: 'cdi.kubevirt.io/v1beta1'
      kind: 'DataVolume'
      metadata:
        creationTimestamp: null
        name: 'fedora-tomcat-xpk'
      spec:
        source:
          pvc:
            name: 'fedora40-base'
            namespace: 'tomcat-virt-app'
        storage:
          resources:
            requests:
              storage: '30Gi'
  running: false
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: 'small'
        vm.kubevirt.io/os: 'fedora'
        vm.kubevirt.io/workload: 'server'
      creationTimestamp: null
      labels:
        kubevirt.io/domain: 'fedora-tomcat-xpk'
        kubevirt.io/size: 'small'
    spec:
      architecture: 'amd64'
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: 'virtio'
              name: 'rootdisk'
            - disk:
                bus: 'virtio'
              name: 'cloudinitdisk'
          interfaces:
            - masquerade: {}
              model: 'virtio'
              name: 'default'
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: 'pc-q35-rhel9.2.0'
        memory:
          guest: '4Gi'
        resources: {}
      networks:
        - name: 'default'
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: 'fedora-tomcat-xpk'
          name: 'rootdisk'
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: fedora
              chpasswd: { expire: False }
          name: 'cloudinitdisk'
      # accessCredentials:
      #   - sshPublicKey:
      #       propagationMethod:
      #         configDrive: {}
      #       source:
      #         secret:
      #           secretName: authorized-keys 
