apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: install-tomcat
  namespace: tomcat-virt-app
spec:
  params:
    - description: Name of a VM to execute the action in.
      name: vmName
      type: string
    - description: Namespace of a VM to execute the action in. (defaults to active namespace)
      name: vmNamespace
      type: string
      default: ""
    - description: Secret to use when connecting to a VM.
      name: secretName
      type: string
      default: "__empty__"
    - description: Command to execute in a VM.
      name: command
      type: array
      default: string
    - description: Arguments of a command.
      name: args
      type: string
      default: ""
    - description: Script to execute in a VM.
      name: script
      type: string
      default: ""
  tasks:
    - name: install-tomcat
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: execute-in-vm
          - name: namespace
            value: virtualization-pipelines