apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: install-tomcat
  namespace: tomcat-virt-app
spec:
  tasks:
    - name: install-tomcat
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: execute-in-vm
          - name: namespace
            value: virtualization-pipelines