apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-shell
spec:
  params:
    - name: command_name
      type: string
      default: date
  results:
    - name: command_result
      description: Salida del comando ejecutado
  workspaces:
    - name: source
      optional: true
      description: Workspace del task
  steps:
    - name: shell
      image: registry.access.redhat.com/ubi9:9.3-1610
      script: |
        #!/bin/bash
        ls -R /workspace/
        "$(params.command_name)" | tee "$(results.command_result.path)"
