apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-shell
  namespace: tkn-text
spec:
  steps:
    - name: uname
      image: registry.access.redhat.com/ubi9:9.3-1610
      script: |
        #!/bin/bash
        uname -a