apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-git-api
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 25Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem